run:
  timeout: 5m
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  govet:
    check-shadowing: false
  gocyclo:
    min-complexity: 20
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports

issues:
  exclude:
    - path: backend/pkg/migrations/postgres/migration.go
      linters:
        - typecheck
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocyclo
    - text: "Error return value of .((os\\.)?std(out|err)\\..*|.*\\.Close|.*\\.Flush|os\\.Remove(All)?|.*\\.Printf?|os\\.(Un)?Setenv). is not checked"
      linters:
        - errcheck

